VPixx

In [1]:
%load_ext autoreload
%autoreload 2

# load VPixx libraries
from pgl import pglProPixx
from pgl import pglDataPixx
from pgl import pglTrackPixx3
import numpy as np

# Load PGL libraries and start a PGL window
from pgl import pgl as pglLibrary
pgl = pglLibrary()

# close any existing windows
pgl.cleanUp()

# open a new window
pgl.open(0,800,600)
pgl.visualAngle(57,60,40)
#pgl.flipLeftRight(True)

(pgl) Warning: pylink not found, pglEyelink class will not be available. Download with: pip install sr-research-pylink
================================ pglBase: init =================================
(pgl) mglMetal error log can be viewed in MacOS Console app by searching for PROCESS mglMetal or in a terminal with:
      log stream --level info --process mglMetal
(pgl) To search for something specifc, e.g. messages from mglMovie:
      log stream --predicate 'eventMessage CONTAINS "mglMovie"' --style syslog --level info
(pgl:checkOS) Python version: 3.12.13 | packaged by conda-forge | (main, Mar  5 2026, 17:06:14) [Clang 19.1.7 ]
(pgl:checkOS) Running on Mac Studio (Mac16,9) with macOS version: 26.5.2
(pgl:checkOS) Apple M4 Max Cores: 14 (10 Performance and 4 Efficiency) Memory: 36 GB
(pgl:checkOS) GPU: Apple M4 Max (Built-In) 32 cores, Metal 4 support
(pgl:checkOS)   DELL U2724DE [Main Display]: 2560 x 1440 (QHD/WQHD - Wide Quad High Definition) (Unknown type) GammaTable size: 1024
(p

Need to make sure that pypixx library is installed. It is now installed on Koret computer, but had to do some shenanigans to get it into the conda environment, I think because it lives in a shared folder:

(pgl) justin@DN0a237c7d pgl % cp -r /Users/Shared/koret_software/miniforge3/envs/gru/lib/python3.13/site-packages/pypixxlib /Users/Shared/koret_software/miniforge3/envs/pgl/lib/python3.12/site-packages/
(pgl) justin@DN0a237c7d pgl % cp -r /Users/Shared/koret_software/miniforge3/envs/gru/lib/python3.13/site-packages/pypixxlib-*.dist-info /Users/Shared/koret_software/miniforge3/envs/pgl/lib/python3.12/site-packages/

I am working off of the demos that are found [here](https://docs.vpixx.com/python/a-comprehensive-trackpixx3-calibration)

You can find the examples by locating the pypixxlib:  pip show -f pypixxlib | grep -i location
On Koret it is here: /Users/Shared/koret_software/miniforge3/envs/pgl/lib/python3.12/site-packages/pypixxlib

Then the examples are in:

/Users/Shared/koret_software/miniforge3/envs/pgl/lib/python3.12/site-packages/pypixxlib/examples

Using the example: [TPxCalibrationTesting.py](/Users/Shared/koret_software/miniforge3/envs/pgl/lib/python3.12/site-packages/pypixxlib/examples/TPxCalibrationTesting.py)



In [10]:
# initialize the track pixx device and check status
trackPixx3 = pglTrackPixx3(pgl)
#trackPixx3.status()

# Initialize dataPixx 
dataPixx = pglDataPixx()
# add to pgl, so that pgl.poll() will return button press events
pgl.devicesAdd(dataPixx)

(pglTrackPixx3) Wake up TrackPixx3
(pglTrackPixx3) TPxIsAwakePictureRequest: 1
(pglTrackPixx3) TPxIsAwakePictureRequest: 1
(pglTrackPixx3) TrackPixx3 initialized with LED intensity 8 and lens 50 mm.
(pglEyeTracker) Eye tracker TrackPixx3 shutdown.
(pglDataPixx) DATAPixx3 FULL
              serial #: 11020-2207, assembly revision: 1.0, firmware revision: 27
              device time: 8254.22258265, cpu time: 235897.15552395835
(pglDevices) Added device: DataPixx


Next, we should be able to calibrate eye image. running calibrateEyeImage should show the subject's eye on the pgl screen in real time.

In [13]:
# calibrate eye image
trackPixx3.calibrateEyeImage()
#trackPixx3.getError()
#trackPixx3.dp.TPxSetLEDIntensity(8)
#print(trackPixx3.dp.TPxGetLEDIntensity())
#trackPixx3.getCameraImage()
#Image.fromarray(trackPixx3.getCameraImage()).show()
#pgl.poll()

(pglEyeTracker) Eye tracker TrackPixx3 shutdown.
(pglEyeTracker) Eye tracker TrackPixx3 shutdown.
(pglTrackPixx3) TrackPixx3 calibrating eye image with LED intensity 8 and lens 50 mm.
(pglTrackPixx3:calibrateEyeImage) Initial time: 8297.81747661 8297.81747661
(pglTrackPixx3:calibrateEyeImage) Increased LED intensity to 8.
(pglTrackPixx3:calibrateEyeImage) Unknown event: (pglEventResponsePixx) Code: 64512, ID: button release, Device Time: 23.01
(pglTrackPixx3:calibrateEyeImage) Increased LED intensity to 8.
(pglTrackPixx3:calibrateEyeImage) Unknown event: (pglEventResponsePixx) Code: 64512, ID: button release, Device Time: 23.45
(pglTrackPixx3:calibrateEyeImage) Exiting calibrate eye image loop


In [ ]:
(calibrationPoints, rawEyePosition) = trackPixx3.calibrateEyePosition(nCalibrationPoints=5,calibrationWidth=5,calibrationHeight=5ß)

(pglTrackPixx3:calibrateEyePosition) Press red button to start calibration or white button to exit
(pglTrackPixx3:calibrateEyePosition) Calibration started.
(pglTrackPixx3:calibrateEyePosition) Calibration point 1/5 at (0.0, 0.0)
[9998.0, 9998.0, 9998.0, 9998.0, -7.74609375, 26.38671875, -5.1640625, 25.7421875, 0.0]
(pglTrackPixx3:calibrateEyePosition) Eye data for calibration point 1 acquired: [-7.6854248  26.25891113 -5.12939453 25.46936035]
(pglTrackPixx3:calibrateEyePosition) Calibration point 2/5 at (0.0, 10.0)
[9998.0, 9998.0, 9998.0, 9998.0, 127.99609375, 127.99609375, -5.11328125, 31.92578125, 0.0]
(pglTrackPixx3:calibrateEyePosition) Eye data for calibration point 2 NOT succesfully acquired. Trying again... [0. 0. 0. 0.]
(pglTrackPixx3:calibrateEyePosition) Calibration point 3/5 at (10.0, 0.0)
[9998.0, 9998.0, 9998.0, 9998.0, -14.1171875, 26.2109375, -11.07421875, 25.91015625, 0.0]
(pglTrackPixx3:calibrateEyePosition) Eye data for calibration point 3 acquired: [-14.12670898  2

In [15]:
print(rawEyePosition)


calibrationsCoeff = trackPixx3.dp.TPxGetCalibCoeffs()
coeffXR = calibrationsCoeff[0:9]
coeffYR = calibrationsCoeff[9:18]
coeffXL = calibrationsCoeff[18:27]
coeffYL = calibrationsCoeff[27:36]

if False:
    np.save("/Users/justin/Desktop/calibrationCoeff.npy",calibrationsCoeff )
    np.save("/Users/justin/Desktop/rawEyePosition.npy",rawEyePosition)
    np.save("/Users/justin/Desktop/calibrationPoints.npy",calibrationPoints)

np.any(rawEyePosition[0]==0.0)

[[ -7.6854248   26.25891113  -5.12939453  25.46936035]
 [  0.           0.           0.           0.        ]
 [-14.0670166   26.22119141 -11.19824219  26.05566406]
 [ -7.60888672  20.9453125   -4.56762695  20.79650879]
 [ -1.58764648  26.27026367   0.           0.        ]]


np.False_

In [ ]:
trackPixx3.displayCalibration(calibrationPoints,rawEyePosition)

In [ ]:
calibrationPoints = np.load("/Users/justin/Desktop/calibrationPoints.npy")
calibrationsCoeff = np.load("/Users/justin/Desktop/calibrationCoeff.npy")
rawEyePosition = np.load("/Users/justin/Desktop/rawEyePosition.npy")

In [ ]:
# init proPixx projector and DataPixx
projector = pglProPixx()


In [ ]:
pgl.devicesAdd(datapixx)

In [ ]:
# check status
projector.status()
datapixx.status()

With the datapixx running, then when you do poll, you should get back what buttons were pressed

In [ ]:
# check button presses
datapixx.poll()

If you enableButtonSchedules, it should turn button presses into digital outputs (see code for details)

In [ ]:
# try to enable button schedule - which should convert buttons into digital outputs
#datapixx.enableButtonSchedules()
#datapixx.enablePixelMode()
datapixx.setupDigitalOutput()

In [ ]:
import pypixxlib._libdpx as dp

In [ ]:

#from pypixxlib.propixx import PROPixx
#pgl.verbose=1
#projector = pglProPixx()
#datapixx = pglDataPixx()

for i in range(1000):
    events = pgl.poll()
    #events = datapixx.poll()
    if events is not None:
        for event in events:
            print(event)
    pgl.waitSecs(0.1)
#datapixx.setupDigitalOutput()
#datapixx.test()
#for i in range(5):
#    print(f"Polling DataPixx: {i}")
    #datapixx.poll()
    #pgl.waitSecs(1)


#device.setRearProjection(True)
#from pypixxlib.propixx import PROPixx
#propixx = PROPixx()
#propixx.getDlpSequencerProgram()
#projector.status()
#print(device)
#from pgl.pglDevice import pglDevice, pglProPixx
#huh = pglDevice(pgl,'huh')
#duh = pglProPixx(pgl)